#define ERT_HAVE_ZLIB
#define ERT_HAVE_ISFINITE
#define ERT_HAVE_GETOPT
#define ERT_HAVE_UNISTD
#define ERT_HAVE_SPAWN
#define ERT_HAVE_THREAD_POOL
#define ERT_HAVE_OPENDIR
#define ERT_HAVE_SYMLINK
#define ERT_HAVE_READLINKAT
#define ERT_HAVE_READLINKAT_DECLARATION
#define ERT_HAVE_GLOB
#define ERT_HAVE_GETUID
#define ERT_HAVE_REGEXP
#define ERT_HAVE_LOCKF
#define ERT_TIME_T_64BIT_ACCEPT_PRE1970
/* #undef ERT_WINDOWS_LFS */
/* #undef ERT_HAVE_PING */
/* #undef PING_CMD */


