#!/usr/bin/env python
import sys

if __name__ == '__main__':
    output_file = sys.argv[1]
    idx = int(sys.argv[2])

    data = {'A': 1, 'B': 2}
    with open(output_file, 'w') as f:
        for key, value in data.items():
            f.write('{} {}\n'.format(key, value*idx))
